"""Fourth Migration - add email column to the app db users table

Revision ID: 1efcae6c0064
Revises: a1a8a416aae3
Create Date: 2019-10-22 09:38:24.395914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1efcae6c0064'
down_revision = 'a1a8a416aae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=70), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
