"""Pitches and Comments

Revision ID: 2efaf66e0f9e
Revises: 82f6bf790f3b
Create Date: 2019-10-23 02:27:28.714992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2efaf66e0f9e'
down_revision = '82f6bf790f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pitches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('pitch', sa.String(length=255), nullable=True),
    sa.Column('comments_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comments_id'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('comments_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('pitches_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'pitches', ['pitches_id'], ['id'])
    op.create_foreign_key(None, 'users', 'comments', ['comments_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'pitches_id')
    op.drop_column('users', 'comments_id')
    op.drop_table('pitches')
    op.drop_table('comments')
    # ### end Alembic commands ###
