"""update pitches-table

Revision ID: 41ed91cc1345
Revises: 6a8ad6f114df
Create Date: 2019-10-23 10:56:14.601565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ed91cc1345'
down_revision = '6a8ad6f114df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
