"""update db tables and relationships

Revision ID: 6a8ad6f114df
Revises: ff9da0c815a4
Create Date: 2019-10-23 10:50:32.431495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a8ad6f114df'
down_revision = 'ff9da0c815a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comments', sa.Column('pitches_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('users_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['users_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'pitches', ['pitches_id'], ['id'])
    op.add_column('pitches', sa.Column('pcategory_id', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('users_id', sa.Integer(), nullable=True))
    op.drop_constraint('pitches_comments_id_fkey', 'pitches', type_='foreignkey')
    op.create_foreign_key(None, 'pitches', 'users', ['users_id'], ['id'])
    op.create_foreign_key(None, 'pitches', 'pcategories', ['pcategory_id'], ['id'])
    op.drop_column('pitches', 'comments_id')
    op.drop_constraint('users_pitches_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'pitches_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pitches_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_pitches_id_fkey', 'users', 'pitches', ['pitches_id'], ['id'])
    op.add_column('pitches', sa.Column('comments_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.create_foreign_key('pitches_comments_id_fkey', 'pitches', 'comments', ['comments_id'], ['id'])
    op.drop_column('pitches', 'users_id')
    op.drop_column('pitches', 'pcategory_id')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'users_id')
    op.drop_column('comments', 'pitches_id')
    op.drop_table('pcategories')
    # ### end Alembic commands ###
