"""upgrade the db relationships

Revision ID: ff9da0c815a4
Revises: 2efaf66e0f9e
Create Date: 2019-10-23 03:22:55.814810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9da0c815a4'
down_revision = '2efaf66e0f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_comments_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'comments_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('comments_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_comments_id_fkey', 'users', 'comments', ['comments_id'], ['id'])
    # ### end Alembic commands ###
